### PR TITLE
feat: add fundingReason field to PostFunding Classes

### PR DESCRIPTION
**Pull request by CaiWillis**
TIS21-6498: Add fundingReason field to PostFunding in TCS

### CODE REVIEW

**Review by hihilary — COMMENTED** [review]
Looks good to me. I'm just wondering if you want to verify this field in `PostFundingResourceIntTest`.

**Comment by CaiWillis** [comment]
Sonar Analysis appears to be failing on changes to existing DTO and Entity Classes, is it worth addressing in this PR?

**Comment by hihilary** [comment]
> Sonar Analysis appears to be failing on changes to existing DTO and Entity Classes, is it worth addressing in this PR?

Removing `equals()` and `hashCode()` methods in DTO and entity should resolve the failed test coverage, but we have to check the callers and make sure no overriddens are required. 
I remember previously the DTOs are not acount for test coverage and I guess there might have been some config changes on SonarCloud. 

I'm okay if you would like to keep them as they are.

**Review by hihilary — CHANGES_REQUESTED** [review]
tcs-api needs a version bump.

**Review by hihilary — APPROVED** [review]

**Pull request merged**
