### PR TITLE
feat: delete duplicate person records

### PR DESCRIPTION
**Pull request by hihilary**
Also checked `PersonTrust`, `PersonView`, `ProgrammeMembership`, `Placement`, `PlacementSupervisor`, `Assessment`, `TrainerApproval` and `Document`. The id of the duplicate person records are not referenced by these tables.

TIS21-2462

### CODE REVIEW

**Review by JosephKelly — APPROVED** [review]
Based on `/src/main/tcs-service/src/main/resources/db/migration/data/hee/V4.8__deleteIncorrectDuplicatePersonRecords.sql` I checked the `Absence` table as well which was didn't have any of these IDs.

**Comment by hihilary** [comment]
> Based on `/src/main/tcs-service/src/main/resources/db/migration/data/hee/V4.8__deleteIncorrectDuplicatePersonRecords.sql` I checked the `Absence` table as well which was didn't have any of these IDs.

@Pepe a.k.a. Joseph thanks for reviewing.
Yesterday, I found the `Absence` table is totally empty, then I checked Admins-UI, looks like Absence once was a functionality in the navbar under People menu, but it has been discarded and removed for quite a while. and I think I've never seen Absence on TIS.

**Review by ReubenRobertsHEE — APPROVED** [review]
LGTM!

**Comment by hihilary** [comment]
> LGTM!

Thanks Reuben, I will merge it after the last deployment succeeds.

**Review by JosephKelly — APPROVED** [review]

**Pull request merged**
